name: compare screenshot comment

on:
  workflow_run:
    workflows:
      - compare screenshot
    types:
      - completed

permissions: { }

jobs:
  Comment-CompareScreenshot:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    timeout-minutes: 2

    permissions:
      actions: read # for downloading artifacts
      contents: write # for pushing screenshot-diff to companion branch
      pull-requests: write # for creating a comment on pull requests

    runs-on: ubuntu-latest

    steps:
      - uses: dawidd6/action-download-artifact@v3
        with:
          name: pr
          run_id: ${{ github.event.workflow_run.id }}
      - id: get-pull-request-number
        name: Get pull request number
        shell: bash
        run: |
          echo "pull_request_number=$(cat NR)" >> "$GITHUB_OUTPUT"
      - name: main checkout
        id: checkout-main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.event.pull_request.base.ref || github.event.repository.default_branch }}
      - id: switch-companion-branch
        env:
          BRANCH_NAME: companion_${{ github.event.workflow_run.head_branch }}
        run: |
          # orphan means it will create no history branch
          git branch -D "$BRANCH_NAME" || true
          git checkout --orphan "$BRANCH_NAME"
          git rm -rf .
      - uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: screenshot-diff
          path: screenshot-diff
      - id: check-if-there-are-valid-files
        name: Check if there are valid files
        shell: bash
        run: |
          # Find all the files ending with _compare.png
          mapfile -t files_to_add < <(find . -type f -name "*_compare.png")
          
          # Check for invalid file names and add only valid ones
          exist_valid_files="false"
          for file in "${files_to_add[@]}"; do
            if [[ $file =~ ^[a-zA-Z0-9_./-]+$ ]]; then
              exist_valid_files="true"
              break
            fi
          done
          echo "exist_valid_files=$exist_valid_files" >> "$GITHUB_OUTPUT"
      - id: push-screenshot-diff
        shell: bash
        if: steps.check-if-there-are-valid-files.outputs.exist_valid_files == 'true'
        env:
          BRANCH_NAME: companion_${{ github.event.workflow_run.head_branch }}
        run: |
          # Find all the files ending with _compare.png
          files_to_add=$(find . -type f -name "*_compare.png")
          
          # Check for invalid file names and add only valid ones
          for file in $files_to_add; do
            if [[ "$file" =~ ^[a-zA-Z0-9_./-]+$ ]]; then
              git add "$file"
            fi
          done
          git config --global user.name ScreenshotBot
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -m "Add screenshot diff"
          git push origin HEAD:"$BRANCH_NAME" -f
      - id: generate-diff-reports
        name: Generate diff reports
        if: steps.check-if-there-are-valid-files.outputs.exist_valid_files == 'true'
        env:
          BRANCH_NAME: companion_${{ github.event.workflow_run.head_branch }}
        shell: bash
        run: |
          # _compare.pngで終わるファイルを検索する
          echo "[_compare.png]で終わるファイルを検索中..."
          files=$(find . -type f -name "*_compare.png")

          # 検索結果をログに出力
          if [[ -z "$files" ]]; then
            echo "該当するファイルが見つかりませんでした。"
            exit 0
          else
            echo "見つかったファイル一覧:"
            echo "$files" | while read -r file; do
              echo "- $file"
            done
          fi

          # 有効なファイルのみをフィルタリング
          valid_files=()
          echo "有効なファイル名を確認中..."
          while read -r file; do
            if [[ "$file" =~ ^[a-zA-Z0-9_./-]+$ ]]; then
              echo "有効なファイル名: $file"
              valid_files+=("$file")
            else
              echo "無効なファイル名: $file"
            fi
          done <<< "$files"

          # 有効なファイルがない場合の対応
          if [[ ${#valid_files[@]} -eq 0 ]]; then
            echo "有効なファイルが見つかりませんでした。"
            exit 0
          fi

          # ランダムな区切り文字を生成
          delimiter="$(openssl rand -hex 8)"
          echo "生成された区切り文字: $delimiter"
          {
            echo "reports<<${delimiter}"
            # Markdownテーブルのヘッダーを作成
            echo "ベースブランチとの差分スナップショットレポート: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.event.pull_request.base.ref || github.event.repository.default_branch }}"
            echo "| ファイル名 | イメージ |"
            echo "|-------|-------|"
          } >> "$GITHUB_OUTPUT"
          echo "MarkdownテーブルヘッダーをGITHUB_OUTPUTに書き込み完了"

          # 有効なファイルを1つずつ処理
          for file in "${valid_files[@]}"; do
            echo "処理中のファイル: $file"
            # ファイル名を取得し、20文字ごとに改行を挿入
            fileName=$(basename "$file" | sed -r 's/(.{20})/\1<br>/g')
            echo "処理後のファイル名: $fileName"
            # テーブル行をGITHUB_OUTPUTに書き込み
            echo "| [$fileName](https://github.com/${{ github.repository }}/blob/$BRANCH_NAME/$file) | ![](https://github.com/${{ github.repository }}/blob/$BRANCH_NAME/$file?raw=true) |" >> "$GITHUB_OUTPUT"
            echo "$file のテーブル行をGITHUB_OUTPUTに書き込み完了"
          done

          # GITHUB_OUTPUTへの書き込み終了
          echo "${delimiter}" >> "$GITHUB_OUTPUT"
          echo "区切り文字をGITHUB_OUTPUTに書き込み完了"
          # スクリプトの終了を示す
          echo "スクリプト実行完了"

      - name: Add or update comment on PR
        uses: peter-evans/create-or-update-comment@v4
        if: steps.generate-diff-reports.outputs.reports != ''
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ steps.get-pull-request-number.outputs.pull_request_number }}
          body: ${{ steps.generate-diff-reports.outputs.reports }}
          edit-mode: replace

      - name: Cleanup outdated companion branches
        run: |
          # Find outdated companion branches with last commit date
          git branch -r --format="%(refname:lstrip=3)" | grep companion_ | while read -r branch; do
            last_commit_date_timestamp=$(git log -1 --format=%ct "origin/$branch")
            now_timestamp=$(date +%s)
            # Delete branch if it's older than 1 month
            # if [ $((now_timestamp - last_commit_date_timestamp)) -gt 2592000 ]; then
            # For testing purpose, delete branch if it's older than 1 second
            echo "branch: $branch now_timestamp: $now_timestamp last_commit_date_timestamp: $last_commit_date_timestamp"
            if [ $((now_timestamp - last_commit_date_timestamp)) -gt 1 ]; then
              # Comment out for demonstration purpose
              echo "Deleting $branch"

              # git push origin --delete "$branch"
            fi
          done